### ISSUE TITLE
This gadget snap fails to build

### ISSUE THREAD

**Issue by ZaneL** [snapcore/pi-gadget#13]
I cloned this repo and ran the following command:

`snapcraft`

![alt text](https://i.ibb.co/PW5Kj20/failed.png "Logo Title Text 1")

**Comment by matthewreimer** [comment]
Same here.

**Comment by sil2100** [comment]
Confirmed. The builds are failing with the newer versions of snapcraft (not the first time when new versions are not completely backward compatible). The fix is easy though - let me push it in a moment.

**Comment by matthewreimer** [comment]
FWIW the following got it building for me the other day, but I haven't tested the resulting snap yet.


[fix.txt](https://github.com/snapcore/pi-gadget/files/4087111/fix.txt)

**Comment by matthewreimer** [comment]
FWIW that patch I used with snapcraft 3.9.7 and pi-gadget rev d3702ea02.
