### ISSUE TITLE
Boot of uc20 on serial port strange

### ISSUE THREAD

**Issue by mvo5** [snapcore/pi-gadget#60]
When I boot uc20 with the pi gadget revision 224 on arm64 on my pi3 I get strange output, see attached screenshot.

Also the hdmi monitor is showing nothing but a blank screen for most of the time (and a little "flash" symbol on the top right). Eventually I do get console-conf on the HDMI and everything seems to be working.

Might be weirdness with my system of course, I use "screen /dev/ttyUSB0 115200" - but the fact that some chars are correct and some are garbled indicates something else is going on.

![Screenshot from 2020-11-27 20-01-50](https://user-images.githubusercontent.com/914418/100478435-7ac34f00-30eb-11eb-8449-bcfaafbc510b.png)

**Comment by tobias-bischoff** [comment]
I had the same issue, resolved it with `screen -U …` to force UTF8.

On Raspberry Pi Video outputs, the (yellow?) flash symbol usually indicates under-voltage, maybe try a beefier power adapter: https://raspberrypi.stackexchange.com/questions/57963/what-does-the-lightning-bolt-mean#57965

**Comment by waveform80** [comment]
The flash symbol is indeed the undervolt warning, and this can certainly cause garbage on the serial line (the serial console is the miniuart which has a baudrate tied to the VPU clock).

**Comment by Meulengracht** [comment]
I'm closing this as this points to be a power supply issue with the pi. We have seen this multiple places and the fix is to use the official power supply (or other proven to work). If there is anything that points to this not being power issue, please reopen.
