### ISSUE TITLE
Does this gadget support the CM4? If not, are you planning to support it?

### ISSUE THREAD

**Issue by nicomt** [snapcore/pi-gadget#67]
Sorry If I'm not supposed to ask questions here, I just didn't know where to ask.

**Comment by RuhanSA079** [comment]
Hello @nicomt 
I am running Core18 on my CM4 with this pi-gadget snap.
So yeah, it seems like it is supported.

**Comment by nicomt** [comment]
@RuhanSA079 Thanks
