### ISSUE TITLE
Please remove 'elevator=deadline' from cmdline.txt

### ISSUE THREAD

**Issue by juergh** [snapcore/pi-gadget#77]
Starting with kernel v5.5 [1], the `elevator=` commandline option is no longer supported and leads to boot warnings:
```
[    0.000000] Kernel parameter elevator= does not have any effect anymore.
               Please use sysfs to set IO scheduler for individual devices.
```

Please remove it from all relevant branches.

[1] https://github.com/torvalds/linux/commit/f8db383507d658c5a729b062c97710efda876cd4

**Comment by waveform80** [comment]
This is dealt with in the classic branch in 3adc1e3c9795faee1b032b4ef99c005ce0b15b48 but I'll close this in a mo once I've dealt with it in the relevant core branches (22-armhf and 22-arm64).
