### ISSUE TITLE
Partition always grows (growpart off ignored) on Ubuntu 21.10 + Jammy daily

### ISSUE THREAD

**Issue by noaho** [snapcore/pi-gadget#85]
Hi, 

On Raspberry Pi since Impish, the partition always grows even if I set the following in user-data of cloud-init.

growpart:
  mode: off
  devices: ['/']

I have tested this on 21.04, and it works, but is broken on 21.10. (partition always grows)

I've also tested this in KVM on amd64, and it works (partition does NOT grow).

I've tested this on the latest jammy raspberry pi daily as at 20210216 and it is also an issue. 

This is a problem for me because I am using runcmd in cloud-init to migrate my drive to LVM/LUKS, and the partitioning step fails because the drive is already full.

I've submitted a ticket to the ubuntu bug tracker, but so far nobody can tell me where the Raspberry Pi modification occur... Is this the correct repo? If not, does anyone have any idea how I can find when the behavior changed and why? Or a lead on which repo I should post this to?

https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1947311

Thanks!
Noah

**Comment by Meulengracht** [comment]
I'm not sure this is a pi-gadget issue as you are not running ubuntu-core, and pi-gadget isn't used for classic images. I'll close this issue unless I hear anything otherwise.

**Comment by noaho** [comment]
No worries.
